import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import SimilatTextGenerator from "@/components/similarTextGenerator";
import { GetServerSideProps, NextPage } from "next";
import { getModels } from "./api/open-ai";

const inter = Inter({ subsets: ["latin"] });

interface HomeProps {
  models: any;
}

const Home: NextPage<HomeProps> = ({ models }) => {
  return (
    <>
      <Head>
        <title>AI text generator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="p-4">
        <div className="text-3xl flex justify-center py-8 pb-32 text-center">
          Similar Text Generator
        </div>
        <div>
          <SimilatTextGenerator />
        </div>
      </div>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  const res = await getModels();
  return {
    props: {
      models: res,
    },
  };
};

export default Home;
